<document> = help | hi | tell-coach | start-coaching |
             stop-coaching | next-question
<help> = "help"
<hi> = "hi"
<start-coaching> = "start coaching", { ws, <"at">, ws, #"(?i)(\d{1,2})(am|pm)" }
<stop-coaching> = "stop coaching"
<next-question> = ("next question" | "another question")
<tell-coach> = "tell coach", ws, text
<ws> = <#'\s+'>
<text> = #"[^\"]*"